services:
  - docker:dind

stages:
  - build_image

variables:
  DOCKER_DRIVER: overlay
  CI_COMMIT_TAG: v0.0.2

build_image:
  stage: build_image
  image: docker:latest
  before_script:
    - echo $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --no-cache -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  after_script:
    - docker logout $CI_REGISTRY

